# Generated by Django 3.1.3 on 2020-12-02 17:44

from django.db import migrations, models
import django.db.models.deletion
import sitio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Primer_Apellido', models.CharField(max_length=30)),
                ('Segundo_Apellido', models.CharField(blank=True, max_length=30)),
                ('Direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('Telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('CorreoElectronico', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20, verbose_name='nombre de Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('pdf', models.FileField(upload_to='uploads', validators=[sitio.models.validate_file_extension], verbose_name='Archivo con Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.cliente', verbose_name='Cliente')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField(default=1)),
                ('Precio', models.PositiveIntegerField(editable=False)),
                ('Observacion', models.CharField(blank=True, max_length=500, verbose_name='Observación')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.pedido', verbose_name='Numero de pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.producto', verbose_name='Producto')),
            ],
        ),
    ]
