# Generated by Django 3.1.3 on 2020-12-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='uploads', verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tablero de pedidos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitio.pedido',),
        ),
    ]
