# Generated by Django 3.1.3 on 2020-12-13 17:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_images_tablero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
