# Generated by Django 3.1.3 on 2020-12-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20201213_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'imagenes'},
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='Observacion',
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
    ]
